export type Difficulty = 'easy' | 'medium' | 'hard' | 'intermediate' | 'impossible' | 'adventure';

export const words: Record<Exclude<Difficulty, 'adventure'>, string[]> = {
  easy: [
    "cat", "dog", "sun", "run", "jump", "play", "red", "blue", "tree", "book",
    "ball", "fish", "bird", "milk", "cake", "hat", "star", "moon", "rain", "snow",
    "desk", "chair", "pencil", "apple", "grape", "happy", "sad", "fast", "slow",
    "ant", "bee", "bug", "car", "cow", "pig", "fox", "hen", "owl", "bat",
    "arm", "leg", "eye", "ear", "nose", "hand", "foot", "head", "hair", "skin",
    "ace", "age", "air", "all", "and", "any", "are", "ask", "ate", "aye",
    "bad", "bag", "bat", "bed", "big", "bit", "box", "boy", "but", "buy",
    "can", "cap", "car", "cut", "cup", "cry", "day", "did", "die", "dig",
    "eat", "end", "eve", "eye", "far", "fat", "few", "fit", "fly", "for",
    "fun", "gas", "get", "god", "got", "gun", "guy", "had", "has", "hay",
    "her", "him", "his", "hit", "hot", "how", "hug", "ice", "ill", "ink",
    "jar", "job", "joy", "key", "kid", "kit", "law", "lay", "let", "lie",
    "log", "lot", "low", "mad", "man", "map", "may", "men", "met", "mix",
    "mom", "new", "not", "now", "off", "old", "one", "opt", "our", "out",
    "owe", "own", "pay", "peg", "pen", "pet", "pie", "pig", "pin", "pit",
    "put", "ran", "rat", "raw", "red", "rid", "rip", "rob", "rod", "row",
    "rub", "rug", "run", "sad", "sat", "saw", "say", "sea", "see", "set",
    "she", "sit", "six", "sky", "son", "sub", "sum", "sun", "tab", "tag",
    "tax", "tea", "ten", "the", "tie", "tip", "ton", "too", "top", "toy",
    "try", "two", "use", "van", "war", "was", "wax", "way", "wet", "who",
    "why", "wig", "win", "wit", "won", "yes", "yet", "you", "zoo", "zap",
    "ace", "act", "add", "ago", "aid", "aim", "ale", "amp", "ape", "arc",
    "ark", "ash", "asp", "awe", "axe", "ban", "bar", "bay", "bee", "bet",
    "bid", "bin", "boa", "bog", "bow", "bud", "bum", "bus", "cab", "cam",
    "cod", "cog", "cop", "cot", "cub", "cud", "cue", "dam", "dew", "dim",
    "dip", "dot", "dry", "due", "dug", "dye", "ebb", "eel", "ego", "elf",
    "elk", "elm", "emu", "era", "err", "ewe", "fad", "fan", "fax", "fed",
    "fee", "fib", "fig", "fin", "fir", "fix", "foe", "fog", "fox", "fry",
    "fur", "gag", "gal", "gap", "gay", "gel", "gem", "gnu", "gum", "gut",
    "gym", "hag", "ham", "hem", "hen", "hew", "hex", "hid", "hip", "hog",
    "hop", "hub", "hue", "hum", "hut", "icy", "imp", "inn", "ion", "ire",
    "irk", "ivy", "jab", "jag", "jam", "jaw", "jay", "jet", "jig", "jog",
    "jug", "keg", "ken", "lab", "lad", "lag", "lap", "lax", "lea", "led",
    "leg", "lid", "lip", "lit", "mac", "mag", "mar", "mat", "max", "mid",
    "mob", "mod", "mop", "mud", "mug", "nag", "nap", "net", "nil", "nip",
    "nod", "nor", "nub", "nun", "nut", "oak", "oar", "oat", "odd", "ode",
    "oft", "oil", "orb", "ore", "pac", "pad", "pal", "pan", "par", "paw",
    "pax", "pea", "pep", "per", "pew", "pod", "pop", "pot", "pox", "pub",
    "pun", "pup", "pus", "rad", "rag", "ram", "rap", "roe", "rot", "rue",
    "rum", "rut", "sac", "sag", "sap", "sew", "sex", "shy", "sin", "sip",
    "sir", "sis", "ska", "ski", "sly", "sob", "sod", "sop", "spa", "spy",
    "tab", "tad", "tan", "tap", "tar", "tat", "toe", "tot", "tub", "tug",
    "tux", "urn", "vat", "vet", "vex", "via", "vie", "vow", "wad", "wag",
    "web", "wed", "wee", "yak", "yam", "yap", "yaw", "yea", "yew", "yin",
    "zap", "zen", "zip"
  ],
  medium: [
    "planet", "rocket", "garden", "yellow", "purple", "friend", "school", "winter",
    "summer", "spring", "autumn", "banana", "orange", "doctor", "nurse", "police",
    "driver", "basket", "soccer", "tennis", "window", "bottle", "cookie", "bridge",
    "forest", "mountain", "ocean", "river", "cloudy", "stormy", "breeze", "shadow",
    "rabbit", "kitten", "turtle", "squirrel", "dolphin", "penguin", "elephant", "giraffe",
    "monkey", "zebra", "leopard", "cheetah", "panda", "koala", "kangaroo", "crocodile",
    "island", "valley", "meadow", "desert", "jungle", "castle", "temple", "palace",
    "market", "museum", "library", "theater", "cinema", "gallery", "station", "airport",
    "bicycle", "motorcycle", "bicycle", "subway", "tunnel", "bridge", "highway", "parking",
    "danger", "puzzle", "mystery", "treasure", "battle", "victory", "defeat", "soldier",
    "player", "leader", "member", "student", "teacher", "worker", "farmer", "artist",
    "author", "singer", "dancer", "actor", "athlete", "trainer", "manager", "painter",
    "guitar", "violin", "trumpet", "flute", "drums", "piano", "harp", "bell",
    "poetry", "drama", "comedy", "tragedy", "action", "adventure", "mystery", "romance",
    "horror", "fantasy", "science", "fiction", "history", "future", "present", "past",
    "silver", "golden", "bronze", "copper", "marble", "crystal", "diamond", "pearl",
    "morning", "evening", "midnight", "sunrise", "sunset", "twilight", "shadow", "light",
    "warmth", "coldness", "darkness", "silence", "noise", "music", "sound", "echo",
    "flavor", "taste", "bitter", "sweet", "salty", "sour", "bitter", "spicy",
    "smooth", "rough", "soft", "hard", "thick", "thin", "wide", "narrow",
    "strong", "weak", "heavy", "light", "bright", "dark", "clear", "cloudy",
    "peaceful", "violent", "gentle", "rude", "kind", "cruel", "loyal", "selfish",
    "honest", "lying", "clever", "stupid", "careful", "careless", "brave", "coward",
    "modern", "ancient", "simple", "complex", "easy", "difficult", "possible", "impossible",
    "mobile", "tablet", "laptop", "desktop", "printer", "scanner", "camera", "video",
    "telephone", "microphone", "speaker", "headset", "monitor", "keyboard", "mouse", "router",
    "storage", "backup", "network", "internet", "website", "software", "hardware", "program",
    "system", "process", "function", "variable", "constant", "array", "string", "object",
    "number", "letter", "symbol", "punctuation", "grammar", "syntax", "language", "dialect",
    "accent", "rhythm", "melody", "harmony", "chord", "note", "scale", "tempo",
    "color", "shade", "tint", "tone", "bright", "dark", "pale", "vivid",
    "shape", "circle", "square", "triangle", "rectangle", "polygon", "sphere", "cube",
    "pattern", "texture", "design", "style", "fashion", "trend", "classic", "modern",
    "quality", "quantity", "measure", "weight", "height", "width", "depth", "length",
    "texture", "material", "fabric", "leather", "metal", "wood", "plastic", "glass",
    "plastic", "rubber", "cotton", "silk", "wool", "linen", "canvas", "denim",
    "surface", "texture", "finish", "polish", "shine", "gloss", "matte", "satin",
    "active", "passive", "dynamic", "static", "moving", "still", "rapid", "slow",
    "sudden", "gradual", "immediate", "delayed", "instant", "eventual", "temporary", "permanent",
    "visible", "invisible", "obvious", "hidden", "clear", "obscure", "apparent", "subtle",
    "natural", "artificial", "genuine", "fake", "authentic", "counterfeit", "real", "unreal",
    "valuable", "worthless", "precious", "common", "rare", "abundant", "scarce", "plentiful",
    "perfect", "imperfect", "flawless", "flawed", "complete", "incomplete", "finished", "unfinished",
    "success", "failure", "triumph", "defeat", "achievement", "disappointment", "progress", "decline",
    "growth", "shrink", "expand", "contract", "increase", "decrease", "rise", "fall",
    "profit", "loss", "earning", "spending", "income", "expense", "budget", "finance",
    "supply", "demand", "market", "trade", "exchange", "commerce", "business", "industry",
    "company", "corporation", "factory", "warehouse", "office", "branch", "division", "department",
    "contract", "agreement", "treaty", "law", "rule", "regulation", "policy", "procedure",
    "justice", "freedom", "liberty", "rights", "duties", "responsibility", "authority", "power",
    "family", "parent", "child", "sibling", "ancestor", "descendant", "relative", "cousin",
    "marriage", "divorce", "wedding", "ceremony", "celebration", "festival", "holiday", "vacation"
  ],
  hard: [
    "beautiful", "adventure", "dinosaur", "chocolate", "butterfly", "umbrella",
    "computer", "keyboard", "scientist", "astronaut", "hospital", "library",
    "building", "vacation", "exercise", "swimming", "language", "history",
    "geography", "arithmetic", "chemistry", "biology", "orchestra", "symphony",
    "mosquito", "volcano", "tornado", "hurricane", "lightning", "thunder",
    "knowledge", "education", "intelligence", "wisdom", "experience", "understanding",
    "responsibility", "participation", "cooperation", "information", "organization", "communication",
    "development", "treatment", "movement", "agreement", "measurement", "government",
    "management", "environment", "improvement", "achievement", "statement", "equipment",
    "investment", "management", "engagement", "encouragement", "excitement", "enjoyment",
    "appointment", "arrangement", "assessment", "assignment", "attachment", "attendance",
    "background", "birthday", "classroom", "classroom", "breakfast", "butterfly",
    "calculation", "celebration", "certainly", "challenge", "character", "chocolate",
    "Christmas", "civilization", "classroom", "collection", "combination", "comfortable",
    "communication", "competition", "complaint", "completely", "complicated", "comprehension",
    "concentration", "conclusion", "condition", "confidence", "congratulation", "connection",
    "consequence", "conservation", "consideration", "construction", "consumption", "contemporary",
    "continuation", "contribution", "conversation", "cooperation", "corporation", "correction",
    "correspondence", "corruption", "creation", "creativity", "creature", "criticism",
    "cultivation", "culture", "currency", "current", "customer", "decoration",
    "definition", "democracy", "demonstration", "departure", "dependence", "description",
    "description", "desertion", "destination", "destruction", "determination", "development",
    "dictionary", "difficulty", "dimension", "direction", "director", "discipline",
    "discovery", "discussion", "disease", "disgust", "dishonest", "disobedience",
    "disposition", "distraction", "distribution", "disturbance", "diversity", "division",
    "document", "domestication", "domination", "downtown", "dramatization", "dreadful",
    "earthquake", "education", "efficiency", "Egyptian", "electricity", "elephant",
    "elevation", "elimination", "emergency", "emission", "emphasis", "employment"
  ],
  intermediate: [
    "opportunity", "intermediate", "achievement", "understand", "absolutely", "literature",
    "recognition", "development", "management", "information", "government", "environment",
    "celebration", "environment", "comfortable", "certificate", "experiment", "conference",
    "independence", "temperature", "encyclopedia", "illustration", "agricultural", "acknowledge",
    "communicate", "performance", "neighborhood", "accommodation", "accommodation", "independent",
    "imagination", "intelligence", "relationship", "encyclopedia", "anniversary", "spectacular",
    "conversation", "organization", "responsibility", "presentation", "relationship", "photograph",
    "microscope", "basketball", "scholarship", "leadership", "championship", "partnership",
    "disappear", "successful", "approximate", "appropriate", "interesting", "entertaining",
    "environment", "embarrassment", "accomplish", "appointment", "accountant", "recommend",
    "sufficient", "requirement", "consequence", "accordance", "accomplishment", "appreciation",
    "acceleration", "acceleration", "accommodation", "alphabetical", "astronomical", "attachment",
    "arrangement", "attraction", "availability", "background", "blackboard", "brainwashing",
    "breadcrumbs", "brotherhood", "brownstone", "candidate", "capitalist", "casserole",
    "catastrophe", "celebration", "cellulite", "centipede", "centralize", "centralizer",
    "centrifuge", "centripetal", "ceremonial", "certificate", "certification", "challenged",
    "challenger", "champagne", "championship", "chandelier", "changeable", "changeover",
    "channel", "chaperone", "chaplain", "characterize", "charades", "charcoal",
    "guardsman", "guardianship", "guerrilla", "guillotine", "guitar", "guiltless"
  ],
  impossible: [
    "accomplish", "accumulation", "acknowledge", "acknowledgment", "administrator", "adolescence",
    "adventurous", "advertisement", "agricultural", "agriculture", "alphabetical", "alphabetically",
    "ambidextrous", "ambassador", "amphibious", "amphitheater", "anachronism", "anaesthetic",
    "analgesic", "analogous", "analogously", "analysis", "analyze", "anarchist",
    "anarchistic", "anarchistic", "anarchy", "anatomical", "anatomically", "anatomist",
    "anatomy", "ancestor", "ancestral", "ancestry", "anchorman", "anchorwoman",
    "anchovies", "anchorageanchorite", "ancient", "ancients", "ancillary", "anconeal",
    "androecium", "androgynous", "android", "anecdotal", "anecdotally", "anecdote",
    "anemia", "anemone", "anesthetic", "aesthetically", "anesthetist", "anesthetize",
    "aneurism", "aneurysm", "anew", "anfractuosity", "anfractuous", "angelic",
    "angelical", "angelically", "angelfish", "angelica", "angelus", "angemosity",
    "angelic", "angioma", "angiospermatous", "angiosperm", "angiostomy", "angiotensin",
    "anglesite", "anglice", "anglican", "anglicanism", "anglicise", "anglicism",
    "anglicize", "angling", "anglophile", "anglophobe", "anglophobia", "angora",
    "angostura", "angry", "angst", "angstrom", "anguine", "anguish",
    "anguished", "angular", "angularity", "angulose", "anhydride", "anhydrite",
    "anhydrous", "aniconic", "aniconism", "anil", "aniline", "aniling",
    "anilline", "anillose", "anilous", "anility", "anima", "animadversion",
    "animadvert", "animal", "animalcule", "animalculum", "animalism", "animalistic",
    "animalize", "animality", "animally", "animals", "animalvore", "animatedly",
    "animatedness", "animater", "animatingly", "animation", "animationism", "animationist",
    "animatism", "animatistic", "animator", "animatorship", "animato", "animatrice",
    "animatronic", "anime", "animism", "animist", "animistic", "animistically",
    "animize", "animosities", "animosity", "animus", "anion", "anionic",
    "anionically", "anise", "aniseed", "anisette", "anisic", "anisite",
    "anisole", "anisomeric", "anisomer", "anisomerous", "anisometropia", "anisometric",
    "anisotropic", "anisotropically", "anisotropy", "anisyl", "anita", "ankh",
    "ankle", "anklebone", "anklet", "anklets", "anklopedia", "ankose",
    "ankusha", "ankuses", "ankylosed", "ankylose", "ankylosed", "ankyloses",
    "ankylosis", "ankylotic", "anlage", "anlagen", "annas", "annalistic"
  ]
};

export function generateAdventureDeck(): string[] {
  const deck: string[] = [];
  
  // Helper to get random unique words
  const getRandom = (list: string[], count: number) => {
    const shuffled = [...list].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
  };

  deck.push(...getRandom(words.easy, 5));
  deck.push(...getRandom(words.medium, 5));
  deck.push(...getRandom(words.hard, 5));
  deck.push(...getRandom(words.intermediate, 3));
  deck.push(...getRandom(words.impossible, 2));
  
  return deck;
}
